---
title: "Todo list"
author: "Chu-Chang"
date: "2017/01/07"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## From Script to model definition
- [x] script to model definition
- [] Stat flow visualisation

## Check Parameters and suggest model type
- [x] Check vector of parameters
- [] Check list of parameters
- [] Select model type

## Build Models
- [x] Deterministic Maarkov Chain Model Construction
- [x] Deterministic Maarkov Chain Model Simulation

- [x] Stochastic Maarkov Chain Model Construction
- [x] Stochastic Maarkov Chain Model Simulation

- [x] Ordinary Differential Equation Model Construction
- [x] Ordinary Differential Equation Model Simulation

- [] Stochastic Differential Equation Model Construction
- [] Stochastic Differential Equation Model Simulation

- [x] Individual Based Model Construction
- [x] Individual Based Model Simulation

## Output
- [] Time Series visualisation

 



